### ISSUE TITLE
Dedicated package for Thor solo accounts and constants

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#1031]
DOD:

- [ ] Create a package with most important constants
- [ ] Add into this package all useful stuff of thor solo node
- [ ] Improve documentation available for the usage of solo

User Story:
* As an user I want to have all constants in a single place
* As an user I want to have all needed accounts and constants of Thor solo into a dedicated package

**Comment by victhorbi** [comment]
As discussed, the work you've done is worthwhile, but let's move it in Network, as suggested by @fabiorigam .
