### ISSUE TITLE
Identify the required RPC Methods still not supported

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1048]

**Comment by nwbrettski** [comment]
Need to identify whether there are any more RPC endpoints that we must support as part of the full launch at the end of the year. https://vechain.atlassian.net/wiki/spaces/TS/pages/379781124/JSON+RPC+Methods

**Comment by victhorbi** [comment]
requires external input

**Comment by victhorbi** [comment]
I've reported here the missing methods that can allow big dapps to move over
[confluence-page](https://vechain.atlassian.net/wiki/x/BACjFg)

**Comment by victhorbi** [comment]
Research done, we will have a readout in September.
