### ISSUE TITLE
🐛 [BUG] - typing for methods is not available when loading a contract

### ISSUE THREAD

**Issue by akanoce** [vechain/vechain-sdk-js#1053]
### Description

Looks like some methods of the class returned via 

`new Contract(....)` are not typed, making it difficult to work with such methods, requiring different `ts-ignore` to silence ts.

<img width="393" alt="Screenshot 2024-07-11 at 10 30 38" src="https://github.com/vechain/vechain-sdk-js/assets/15635248/89958ee5-d705-45cb-9668-297928fb2336">

<img width="463" alt="Screenshot 2024-07-11 at 10 30 45" src="https://github.com/vechain/vechain-sdk-js/assets/15635248/bab09147-93ac-4650-9055-d4e68e379cea">

As you can see in both screenshots, the Contract is just a generic `Contract<Abi>`. I tried with multiple abis and contracts achieving the same result 

### Reproduction steps

1.  Copy [this json](https://github.com/vechain/b32/blob/master/ABIs/VeBetterDAO-x-allocations-voting.json) and assign it to a variable in your local `const abi = [...]`
2. Define the contract address `const address = "0x89A00Bb0947a30FF95BEeF77a66AEdE3842Fe5B7"`
3. Instantiate the thorClient 
`const thorClient = ThorClient.fromUrl("https://mainnet.vechain.org");`
4. Instantiate the contract class 
```
  const allocationContract = new Contract(
    address,
    abi,
    thorClient
  );
```
4. See the errors like attached. No method is available using `.read` and `.clause`

### OS

Mac

**Comment by Valazan** [comment]
There is something odd in the ABI that was provided, if I load the one from the vebetterdao package, the typings works as expected. 

<img width="764" alt="Screenshot 2024-07-26 at 18 57 19" src="https://github.com/user-attachments/assets/8ea92de5-5250-4aee-abd2-a6982b22535b">

@akanoce can you confirm it's still a bug and not a problem with the abi provided?

**Comment by fabiorigam** [comment]
Waiting for @akanoce feedback

**Comment by akanoce** [comment]
@Valazan @fabiorigam it's still not working on my side guys.
I tried with lot of different abis, without luck (i.e https://github.com/vechain/b32/blob/master/ABIs/VeBetterDAO-b3tr.json)

- I Updated to beta-26;
- I Performed a clean install;

Also, i really think we should infer the type instead of having the user manually declare it like

`Contract<type of json.abi>`


which, is trowing type errors in my case

<img width="688" alt="Screenshot 2024-08-01 at 18 09 55" src="https://github.com/user-attachments/assets/0e00fcee-01d0-48a3-9941-eb65c9187864">
<img width="589" alt="Screenshot 2024-08-01 at 18 09 47" src="https://github.com/user-attachments/assets/d3d0e232-c387-496f-8124-f0da40ecea0e">

**Comment by Valazan** [comment]
@akanoce we have to check it better because the type is directly imported from abitype https://abitype.dev/, so it's not something implemented by SDK.

As for the loading, the standard way to load a contract is:

``` typescript
        const loadedContract = thorSoloClient.contracts.load(
            contract.address,
            contract.abi
        );
```

In this case type will be inferred. But we can also see it implemented for a new contract object instantiation

**Comment by fabiorigam** [comment]
Opened a new PR with a releted issue, this one is working
