### ISSUE TITLE
Collect all requirements for eth_getLogs

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#1072]
To have 'logIndex' and 'transactionIndex', we need to query a block for each entry into the logs.
After from the block, we can get the transaction index and the log index.
This is a performance issue because we have to query a block for each entry into the logs.
So, the best is to implement it protocol side

**Comment by rodolfopietro97** [comment]
@victhorbi 

* Input and behaviour to eth_getLogs: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getlogs
* Output of eth_getLogs: https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getfilterchanges
* Code: https://github.com/vechain/vechain-sdk-js/blob/1d488b389704b591f9d30377bd4b00af3683e826/packages/network/src/provider/utils/formatter/logs/formatter.ts#L26

**Comment by victhorbi** [comment]
Protocol team will make the information available on the client.
