### ISSUE TITLE
Investigate random number generation by serverless cloud providers

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1092]

**Comment by ifavo** [comment]
Maybe it is worth looking at how `ethers` does the signing, because signing with `ethers` does work on CloudFlare.

**Comment by victhorbi** [comment]
thanks @ifavo , your suggestion may represent a good shortcut.

**Comment by fabiorigam** [comment]
The solution is to use the polyfill as suggested here: https://github.com/paulmillr/noble-secp256k1/blob/main/README.md
