### ISSUE TITLE
interface VeChainDataModel

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1103]
The package at `packages/core/src/vcdm` introduces the *VeChain Data Model*.

**Comment by lucanicoladebiasi** [comment]
**VeChain Data Model**

![Image](https://github.com/user-attachments/assets/51d44ef6-4997-41be-8f74-e42535374256)

**Comment by lucanicoladebiasi** [comment]
Transitioning documentation to Mermaid C4/UML...
