### ISSUE TITLE
refactor abi

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1118]

**Comment by freemanzMrojo** [comment]
The current contract is about ABI functions so this class is needed.

**Comment by freemanzMrojo** [comment]
Will migrate from Ethers to [Viem](https://viem.sh/) for ABIs as part of this ticket after discussing it with @lucanicoladebiasi

**Comment by freemanzMrojo** [comment]
This is the branch with my progress @lucanicoladebiasi @victhorbi https://github.com/vechain/vechain-sdk-js/tree/feat/1118-abi-class in case you need something from it.

Please let me finish it! 😛 🙏
