### ISSUE TITLE
🐛 [BUG] - Some RPC methods don't work as expected

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1131]
- [ ] eth_estimateGas
- [ ] eth_getTransactionCount (known)
- [x] eth_gasPrice
- [ ] eth_getCode
- [x] eth_getLogs

```
e.g.
{
    "jsonrpc": "2.0",
    "error": {
        "methodName": "ethGetLogs()",
        "errorMessage": "Method \"ethGetLogs\" failed.",
        "data": {
            "code": -32603,
            "message": "Method \"ethGetLogs\" failed.",
            "data": {
                "params": "[{\"address\":\"0x170f4ba8e7acf6510f55db26047c83d13498af8a\"}]",
                "url": "http://mainnet.vechain.org",
                "innerError": "{\"methodName\":\"HttpClient.http()\",\"errorMessage\":\"Invalid URL: http://mainnet.vechain.org/logs/event\",\"data\":{\"method\":\"POST\",\"url\":\"http://mainnet.vechain.org/logs/event\",\"message\":\"Request failed\"},\"innerError\":{\"methodName\":\"HttpClient.http()\",\"errorMessage\":\"Invalid URL: http://mainnet.vechain.org/logs/event\",\"data\":{\"method\":\"POST\",\"url\":\"http://mainnet.vechain.org/logs/event\",\"status\":405}}}"
            }
        }
    },
    "id": 1
}
```

### Acceptance criteria
Provide also a way to test that the methods satisfy the standard json-rpc 2.0.

**Comment by victhorbi** [comment]
will check again, @leszek-vechain was suggesting that can be just a typo (http vs https).

**Comment by victhorbi** [comment]
@rodolfopietro97 
Seems the only issue here was the schema, the block must be optional. 
Here's the list of where I've found the same issue:

- [ ] eth_getCode
- [ ] eth_gasPrice
- [ ] eth_getTransactionCount
- [ ] eth_getBalance

**Comment by leszek-vechain** [comment]
it seems like we build the clause wrong, I can show you tomorrow (at least for eth_estimateGas) or we transform data wrongly

**Comment by leszek-vechain** [comment]
So this is the body we sent at the moment:

```
{"clauses":[{"to":"0xf077b491b355e64048ce21e3a6fc4751eeea77fa","data":"0x0","value":"100000"}],"caller":"0xf077b491b355e64048ce21e3a6fc4751eeea77fa"}
```

this is the body I sent via postman and it works:
```
{"clauses":[{"to":"0x7567d83b7b8d80addcb281a71d54fc7b3364ffed","data":"0x","value":"0x186a0"}],"caller":"0xf077b491b355e64048ce21e3a6fc4751eeea77fa"}
```

so it seems we transform value from hex to bigint, and data is not properly formatted

**Comment by victhorbi** [comment]
Block parameter is not optional. The ticket can be closed.
