### ISSUE TITLE
Remove backwards compatibility code

### ISSUE THREAD

**Issue by freemanzMrojo** [vechain/vechain-sdk-js#1184]
### Summary

The purpose of this ticket is to remove backwards compatibility code to support the beta versions of the SDK before we release it.

Will refer to this ticket in the comments within the code.

### Basic Example

One example would be at the `Blake2b256.ts` file.

### Tasks
- [ ] Remove all the code required to run legacy software relying on the sdk 
- [ ] Highlight very clearly in the release note

**Comment by victhorbi** [comment]
blocked by #1366
