### ISSUE TITLE
🐛 [BUG] - Review `SONAR_TOKEN` parameter for forked branches

### ISSUE THREAD

**Issue by freemanzMrojo** [vechain/vechain-sdk-js#1186]
### Description

The purpose of this ticket is to review the use of the `SONAR_TOKEN` parameter since for forked branches wont be informed, hence crashing the PR's pipeline.

### Reproduction steps

1. Fork the SDK repo with a GH user without permissions for the Sonar project
2. Create a PR 
3. The pipeline will fail in the Sonar Scan step

### Logs

Check this GH action run https://github.com/vechain/vechain-sdk-js/actions/runs/10489948945/job/29056416080

**Comment by victhorbi** [comment]
@leszek-vechain 
research which are the options we have; we will have a small session with Waqar to move on with a decision.

**Comment by leszek-vechain** [comment]
There is a couple of threads on Sonarcloud forums around it, most pointing to this roadmap:

https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request

It seems it was recently implemented via Automatic Analysis:

https://docs.sonarsource.com/sonarcloud/advanced-setup/automatic-analysis/

Need to dig a bit more into it
