### ISSUE TITLE
🐛 [BUG] - Published NPM packages do not show up if the GitHub user did not sign in

### ISSUE THREAD

**Issue by freemanzMrojo** [vechain/vechain-sdk-js#1216]
### Description

Title is self-explanatory

### Reproduction steps

This is how it is seen by a logged user:

![Screenshot 2024-08-30 at 09 00 29](https://github.com/user-attachments/assets/baaf5058-a2dd-4eef-8d29-a8f553efa62a)

This is how it is seen by an user who did not log in:

![Screenshot 2024-08-30 at 09 00 54](https://github.com/user-attachments/assets/69f27886-65bb-4347-b67a-797910322c0d)

**Comment by victhorbi** [comment]
Done
