### ISSUE TITLE
Publish RPC Proxy docker image to Docker Hub

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1319]
Some considerations:

- Support multiple architectures (arm and amd)
- Provide a `yarn.lock` file for the build phase (this is complicated in a monorepo setup as the yarn.lock is at the root)
- run install with the following params `RUN yarn install --production --frozen-lockfile --ignore-scripts --prefer-offline` (currently doesn't build)

**Comment by victhorbi** [comment]
@daithihearn can you check if the docker is working for you?
From @rodolfopietro97 perspective it should work now.

**Comment by rodolfopietro97** [comment]
This task can be closed after:
* #1378 will be completed
* @daithihearn will test and 💪

@victhorbi

**Comment by victhorbi** [comment]
as @freemanzMrojo was suggesting during the last refinement session, we should add some security layer before publishing on Docker Hub.
@WaqarAhmedVC will be involved to define the proper tools.

**Comment by WaqarAhmedVC** [comment]
We will need the following security tools to scan it before pushing it to Dockerhub:
1. Ensure that socket is enabled on the repo
2. Ensure that there is a sonarcloud project for this in the Sonarcloud portal . (I just checked and it exist. )
3. Ensure that the container is scanned by a container scanner tool such as Trivvy or if it is pushed to AWS ECR, then scanning can be done by AWS ECR. 
4. Ensure that Gitleaks is enabled on this repo to scan for any credentials in the container. 
5. Ask @AlanSower to run github's own security tool to scan for credential (if possible, we are on a trial version and it might expire in a day or two. Please check with Alan)
6. Run Slither tool to security check the contracts that are going to be deployed in this container.

**Comment by AlanSower** [comment]
GitHub's CodeQL for advanced code scanning was ran , no credentials found, all good. 

Socket is working as expected also.

**Comment by victhorbi** [comment]
Missing parts:
- pipeline configuration
- architecture configuration

**Comment by freemanzMrojo** [comment]
GH action will be based on [this config](https://docs.docker.com/build/ci/github-actions/multi-platform/), it is also used in the `thor` repo.

I reached out about the credentials for Docker Hub in the protocol Slack channel and apparently they are repo-based so they would need to be extracted to org level if we want to use them.

**Comment by freemanzMrojo** [comment]
Will be working on this ticket https://github.com/vechain/vechain-sdk-js/issues/1438 while waiting for the credentials config.

**Comment by freemanzMrojo** [comment]
After merging the PR above the only bit missing are the actual credentials for Docker Hub @WaqarAhmedVC @victhorbi .

The job will fail as of now but it could be retried once the credentials are set.

Will close this ticket once that job succeeds.

**Comment by freemanzMrojo** [comment]
It has been finally published in Docker Hub: https://hub.docker.com/r/vechain/sdk-rpc-proxy/tags

In case any issues are found let's continue in a separate issue since this has been opened for a while.
