### ISSUE TITLE
Remove `ethers` from `core` package and review usage of `vechain_sdk_core_ethers`

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1339]
The goal of this ticket is to remove `ethers` from the `core` package since now we are using `viem` (please, have a look at the comments within the package too).

We are currently exporting `ethers` from `core` as `vechain_sdk_core_ethers`. I think we could move `ethers` to the `network` package since it is also imported in the other dependencies (`ethers-adapter`, `hardhat-plugin`). Another ticket to remove `ethers` from `network` will address the removal for this second package.

If `ethers` is used for testing, please consider to place the dependency under `devDependencies` (if used directly, like for `EventFragment#from`) since it could be handy to have it for compatibility purposes.

**Comment by freemanzMrojo** [comment]
Hi @victhorbi @fabiorigam I am gonna amend the description and title of this issue, I have been reviewing the remaining ethers integration and I believe some parts should be addressed first, actually there are very few occurrences of wallet.
