### ISSUE TITLE
DappKit :: Adding options to the signTypedData

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-sdk-js#1367]
To enhance compatibility with extension and mobile and to allow account switching when signing typed data, we should add the following optional options parameter to the signTypedData:

``` typescript

interface SignTypedDataOptions {
  signer?: string;
}

async signTypedData(
    _domain: ethers.TypedDataDomain,
    _types: Record<string, ethers.TypedDataField[]>,
    _value: Record<string, unknown>,
    _options?: SignTypedDataOptions
  ): Promise<string>


```

**Comment by victhorbi** [comment]
I would like to keep this in the RC, since next week people may already start using it.
