### ISSUE TITLE
Wrong version for noble curve in the manifest

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1411]
### Summary

Solve the [manifest confusion](https://socket.dev/alerts/manifestConfusion) reported by Socket.dev

### Basic Example

At https://socket.dev/npm/package/@noble/curves/files/1.6.0/package.json#T1078-1085

**Comment by fabiorigam** [comment]
@victhorbi This is an issue on [@noble/curves](https://socket.dev/npm/package/@noble/curves/files/1.6.0)'s side. THere's nothing we can do.

**Comment by fabiorigam** [comment]
Opened an issue on their package: https://github.com/paulmillr/noble-curves/issues/164

**Comment by victhorbi** [comment]
Confirmed to a Socket.dev issue.
