### ISSUE TITLE
Bump thor-devkit dependencies

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1441]

**Comment by claytonneal** [comment]
If we release thor devkit we will need to re-release everything that depends on it
@fabiorigam @victhorbi do we have such a list?

**Comment by fabiorigam** [comment]
FYI: https://github.com/vechain/thor-devkit.js/commits/master/ I updated a lot of packages.
@claytonneal We will need to use latest version where we are using it, yeah. And so, re-release if needed.

**Comment by fabiorigam** [comment]
Completed: https://github.com/vechain/thor-devkit.js
