### ISSUE TITLE
💡 [REQUEST] - Add support for rpc.`trace_filter`

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#1442]
### Summary

I am in the process of using subgraphs to index function calls. The functionality currently fails because `trace_filter` is not supported with the RPC functionality in the SDK.

Is it possible to add support for it? I am not familiar enough with the internals of the existing trace functionality in the nodes, if they provide sufficient data to fulfill this request.

### Basic Example

```shell
curl -XPOST "http://localhost:8545" -H "content-type: application/json" -d '
{
    "jsonrpc": "2.0",
    "method": "trace_filter",
    "params":  [{"fromBlock":"0x12e7104","toAddress":["0x35a267671d8edd607b2056a9a13e7ba7cf53c8b3"],"toBlock":"0x12e7104"}],
    "id": "1"
}
'
{"jsonrpc":"2.0","id":"1","result":[]}
```

**Comment by victhorbi** [comment]
Hey @ifavo, namespaces `debug` and `trace` are exclusive. You have one or the other based on the client family. We've opted to go with `debug`, like the majority of eth clients.
https://docs.alchemy.com/reference/trace-api-vs-debug-api

Will check what to use in its behalf and get back to you.

**Comment by claytonneal** [comment]
Hi @ifavo the trace_filter method is a method only available on the Erigon ethereum client, it doesnt exist on Go-Ethereum for example.
See: https://docs.chainstack.com/docs/geth-vs-erigon-deep-dive-into-rpc-methods-on-ethereum-clients
Correlating what it does the VeChain Thor API, to me it looks like this method isnt implemented in Thor
Hence from an SDK point of view it cannot be implemented
Happy to chat more - but unless its implemented in the protocol, the SDK wont be able to support it, thanks
