### ISSUE TITLE
🐛 [BUG] - `Class extends value undefined is not a constructor or null`

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#1467]
### Description

After upgrading from beta-32 to 1.0.0-rc.1 I encountered an error in my parcel react applications.

The simplest reproduction is happening when using `subscriptions.getBeatSubscriptionUrl`:

The problem is not restricted to subscriptions, it happens for many other imports as well.

### Reproduction steps

```ts
import { subscriptions } from '@vechain/sdk-network';
subscriptions.getBeatSubscriptionUrl("https://testnet.vechain.org")
```

### Screenshots

![Bildschirmfoto 2024-11-05 um 09 30 55](https://github.com/user-attachments/assets/bce58b9b-c221-40d3-8773-ce9a4107f8e8)

**Comment by ifavo** [comment]
Maybe a different message helps, that pops up when importing the `TransactionsModule` directly:

![Bildschirmfoto 2024-11-05 um 11 39 49](https://github.com/user-attachments/assets/71fff03b-570f-478d-a2c7-ea6ba3017717)

**Comment by freemanzMrojo** [comment]
hi @victhorbi after talking to the guys I will be reviewing this issue myself, so I am going to assign it to me now
