### ISSUE TITLE
💡 [TransactionRequestInput] - Request input is missing the ability to specify some fields required for dapps

### ISSUE THREAD

**Issue by darrenvechain** [vechain/vechain-sdk-js#1483]
### Summary

When specifying the `TransactionRequestInput`, users should be able to specify:

- A comment, describing the transaction
- A delegation URL, to delegate the transaction

### Basic Example

```typescript
const signer = new VeChainAbstractSigner(...)

const tx = await signer.sendTransaction({ comment: "Hello", delegationURL: "https://example.com"})
```

**Comment by freemanzMrojo** [comment]
hi @victhorbi after talking to the guys I will be reviewing this issue myself, so I am going to assign it to me now

**Comment by victhorbi** [comment]
Related to https://github.com/vechain/vechain-sdk-js/pull/1517/
