### ISSUE TITLE
[Test] Fix/Improve flaky tests

### ISSUE THREAD

**Issue by leszek-vechain** [vechain/vechain-sdk-js#1491]
**Description**

There are couple of failing integration testnet tests, mainly connected to signing txs:

https://github.com/vechain/vechain-sdk-js/actions/runs/11722280164/job/32651476812

**Action**

- check if there are no other tests like that (have a look at failing Github action tests)
- select the best way to handle it, there are couple of possible options (from possibly best to worst):
  - reorder the tests, following execution order: https://jestjs.io/docs/setup-teardown#order-of-execution
  - split the test run so instead of one run, we have two - where one is sequential and one is parallel (reporting can be a problem)
  - use --runInBand flag while running jest tests (it works on whole run not single tests: https://jestjs.io/docs/cli#--runinband)
  - run test with single worker (it will slow down run a lot)

**Expected results**
More reliable tests with no random failures

**Comment by freemanzMrojo** [comment]
Taking this one since I built the test in the first place 👍
