### ISSUE TITLE
Update the documentation on reading contracts

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#1550]
There isn't yet described the ability to make a function call that doesn't change the state of the blockchain.

We should include some examples, the current way to do it is via "executeCall".

**Description**

- [x] Update the examples available under `States & View` , since they are using outdated code 
(should be `ABIContract.ofAbi("whatever string you find as abi").getFunction('function name')`)

e.g. 
from 
```
const name = await thor.contracts.executeCall(
  '0x0000000000000000000000000000456e65726779',
  'name() returns (string)'
);
console.log('Name', name);
```
to 
```
const name = await thor.contracts.executeCall(
  '0x0000000000000000000000000000456e65726779',
  ABIContract.ofAbi('name() returns (string)').getFunction('name()')
);
console.log('Name', name);
```
- [x] Add an example file in the vechain-sdk-js repo
- [x] Add the snippet taken from the example above in the official documentation (docs.vechain.org)

**Comment by leszek-vechain** [comment]
Created a PR for docs under: https://github.com/vechain/vechain-docs/pull/85

**Comment by leszek-vechain** [comment]
Added PR for this: https://github.com/vechain/vechain-sdk-js/pull/1559
