### ISSUE TITLE
Util Function :: VTHO instead of Gas

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#264]
As a developer I want to be able to provide my dApp users with transaction costs in terms of VTHO instead of gas so that my dApp users can easily quantify their transaction costs.

Tasks:
- parseGas(amountVTHO: string | number) -> .e.g, parseGas(0.21) = 21000
- formatGas(rawGas: number | string) -> e.g,  formatGas(21000) = 0.21

Acceptance Criteria:
-

**Comment by victhorbi** [comment]
@fabiorigam I think this task is outdated, what do you think?

**Comment by lucanicoladebiasi** [comment]
Dealing with units and quantities should be addressed my the *VeChain Data Model* we are developing in the SDK team, hence I propose to address this ticket as we are developing the data model ontology. Having defined a Quantity class, the classes VTHO and Gas should extends Quantity and cope with conversions/casts.
