### ISSUE TITLE
Docs :: SSD Diagrams

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#378]
As a Contributor I want to be able to view the SSD diagram which offers a higher-level overview of all the packages and macro-systems sequence interactions of each packages and their interactions/dependencies

**Comment by victhorbi** [comment]
@fabiorigam was suggesting to rely on the already existing C4 diagrams, publicly accessible being part of the repo. 
@rodolfopietro97 do you agree with the approach?
This ticket will be closed, and the one for updating C4 diagrams will be created in its behalf.

**Comment by victhorbi** [comment]
The Team is aligned to just use C4 diagram, lower-level diagrams will probably be imported in the single readme files as mermaid diagrams as well.
cc @bgaughran
