### ISSUE TITLE
Build transaction body: add new fields to override

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-sdk-js#383]
## User Story

**As a user, I need the ability to customize various fields when constructing a transaction body for blockchain transactions.**

### Requirements:
- **Custom Block Definition**: Ability to define a custom blockRef within the transaction body
- **Field Customization Flexibility**: Freedom to modify all other necessary fields in the transaction body, ensuring that the transaction aligns with unique requirements and use cases.

## Task Objective

**To address the user's needs, the following steps will be undertaken:**

1. **Analyze Transaction Body Fields**: Conduct a thorough analysis of the current transaction body fields to identify which fields should be made customizable.
2. **Evaluate Implementation**: Assess how to implement this flexibility in a way that maintains the integrity and functionality of the transaction process.

**Comment by nwbrettski** [comment]
Definitions of `blockRef` https://docs.vechain.org/core-concepts/transactions/meta-transaction-features/controllable-transaction-lifecycle

**Comment by lucanicoladebiasi** [comment]
| packages/core/src/transaction/types.d.ts | | packages/network/src/thor-client/transactions/types.d.ts | |
| :--- | :--- | :--- | :--- |
| `TransactionBody` | **Description** | `TransactionBodyOptions` | **Description** |
| `blockRef: string;` | 8 bytes prefix of some block's ID | | |
| `chainTag: number;` | Last byte of genesis block ID | | |
| `clauses: TransactionClause[];` | Array of clauses | | |
| `dependsOn: string \| null;` | D of another tx that is depended | `dependsOn?: string`; | The ID of the transaction that this transaction depends on. |
| `expiration: number;` | Constraint of time bucket | `expiration?: number;` | The expiration time of the transaction. |
| `gas: string \| number;` | Max gas provided for execution |
| `gasPriceCoef: number;` | Coefficient applied to base gas price [0,255] | `gasPriceCoef?: number;` | Coefficient used to calculate the gas price for the transaction. |
| | | isDelegated?: boolean; | Whether the transaction is delegated to another account for gas payment. |
| ` nonce: string \| number; ` | Nonce value for various purposes |
| `reserved?: {}` | [VIP-191](https://github.com/vechain/VIPs/blob/master/vips/VIP-191.md) |

**Comment by lucanicoladebiasi** [comment]
### Questions

- Describe the relation between `TransactionBody` and `TransactionBodyOptions`.
- Identify the official documentation for the API end-point exposed by Thor and accessed by `thorSoloClient`.

**Comment by lucanicoladebiasi** [comment]
### Uses

- packages/network/src/thor-client/transactions/types.d.ts : `TransactionBodyOptions`
   - src  
      - packages/network/src/thor-client/contracts/contracts-module.ts : `executeContractTransaction`
      - packages/network/src/thor-client/contracts/model/contract-factory.ts : `startDeployment`
      - packages/provider/src/providers/vechain-provider/vechain-provider.ts : `sign`
   - tests
      - packages/network/tests/thor-client/transactions/transactions.mocks.solo.test.ts : `describe('buildTransactionBody with mocks'` : `test('Should throw error when genesis block is not found'`
      - packages/network/tests/thor-client/transactions/transactions.mocks.solo.test.ts : `describe('buildTransactionBody with mocks'` : `test('Should throw error when get block is not found'`
      - packages/network/tests/thor-client/transactions/transactions.solo.test.ts : `describe('ThorClient - Transactions Module'` : `describe('signTransactionTestCases'`
      - packages/network/tests/thor-client/transactions/transactions.solo.test.ts : `describe('ThorClient - Transactions Module'` :`describe('buildTransactionBody'`
      - packages/network/tests/thor-client/transactions/transactions.testnet.test.ts : `describe('Transactions module Testnet tests suite'` : `describe('signTransactionTestCases'`
      - packages/network/tests/thor-client/transactions/transactions.testnet.test.ts : `describe('Transactions module Testnet tests suite'` : describe('buildTransactionBody'
      - packages/network/tests/utils/subscriptions/subscriptions.solo.test.ts : `describe('Transactions module Testnet tests suite'` : `describe('buildTransactionBody'`
      - `packages/network/tests/utils/subscriptions/subscriptions.solo.test.ts : `describe('Transactions module Testnet tests suite'` : test('Should receive VET transfers from the VET transfers subscription'`

**Comment by lucanicoladebiasi** [comment]
* `TransactionBodyOptions` includes
   * `blockRef`, if `null` get it from `await this.thor.blocks.getBestBlockRef()`
   * `chainTag`, if `null` get it from `await this.thor.blocks.getBlockCompressed(0)`.
   * `nonce`
* `TransactionBody` and `TransactionBodyOptions` used to generate the first one are sorted to share the same documentation for properties.
* In packages/network/src/thor-client/transactions/transactions-module.ts, the error messages are decorated including class name as prefix of the method.
