### ISSUE TITLE
SDK Compatibility :: Cross-OS Testing and Configuration

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-sdk-js#400]
### User Story
As a developer collaborating on the SDK, I want to test and ensure compatibility across different operating systems so that all potential contributors can seamlessly compile, run tests, and work with the SDK, regardless of their OS.

### Acceptance Criteria:

- [ ] **Linux Compatibility Assessment**: Identify and document the challenges of compiling and running SDK tests on different Linux distributions
  - [ ]  Create a guide detailing the steps and requirements for setting up and running the SDK on Linux distributions with particular focus on Docker.

- [ ] **Windows Compatibility Verification**: Ensure that the SDK and all its components, especially Docker, work flawlessly on Windows.
  - [ ] Conduct tests on Windows to identify any issues with Docker integration.
  - [ ] Develop and document any necessary steps or modifications to facilitate a smooth experience for Windows users.

- [ ] **Test Automation**: Explore the possibility to run the automated test pipeline also on Windows OS.

---

**Comment by fabiorigam** [comment]
Duplicated [#793](https://github.com/vechain/vechain-sdk-js/issues/793)
