### ISSUE TITLE
Thor Client :: option to not stop listening on interval error

### ISSUE THREAD

**Issue by pierobassa** [vechain/vechain-sdk-js#495]
Currently the event poll when the `intervalLoop` encounters an error, it stops the polling. We need to add an option to keep listening in case of errors. 

E.g., connection goes down, the polling stops. If the connection goes back up, polling is still terminated.

**Comment by lucanicoladebiasi** [comment]
In the `packages/network/src/utils/poll/event.ts` the class `EventPoll` has a new `private readonly isToStopOnError: boolean;` property to flag the `_intervalLoop()` if to stop in the case an error is caught.

If an error stop the poll, the code called by the `onError` call back can resume it calling `startListen` or making a new `EventLoop`.
