### ISSUE TITLE
Scouting :: RPC Methods - HIGH Priority - 1

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#512]
- [ ] eth_gasPrice - Understand only if 0x is ok, or we have other alternatives
- [ ] eth_getTransactionCount - Understand only if count is better, instead of nonce
- [ ] web3_clientVersion - Better understand if 'thor' is ok

**Comment by victhorbi** [comment]
Outdated issue. The methods are either supported or partially supported now.
