### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#518]
As a user I want to create browser app that use SDK as dependency.

Issues:

- [x] Issues with webassembly for solc compiler
- [x] Some libraries issues (fs,...) -> Proper configure web pack or remove exporting of this libraries
- [ ] Evaluate https://github.com/browserslist/browserslist
- [x] Issue with noble-hashes and polyfills
- [x] NextJS #974 
- [x] React #983 

Acceptance Criteria:
- The SDK is browser compatible

**Comment by lucanicoladebiasi** [comment]
Defining as
* **pure** : the code agnostic if running in nodejs or in a browser without additional component to adapt runtime to nodejs.
* **secure** : the code we can demonstrate algorithms are cryptographically secure and libraries passed a secure audit.

The code in the repo https://github.com/vechain/vechain-sdk-js/tree/712-derive-public-key-from-wallet-extended-public-key-without-elliptic-library is pure and secure for

* packages/core/src/bloom/bloom.ts
* packages/core/src/hash/blake2b256.ts
* packages/core/src/hash/keccak256.ts
* packages/core/src/hash/sha256.ts

**Comment by lucanicoladebiasi** [comment]
The code at https://github.com/vechain/vechain-sdk-js/tree/666-address-pure-and-secure is pure and secure for

- packages/core/src/address/address.ts

**Comment by lucanicoladebiasi** [comment]
The code at https://github.com/vechain/vechain-sdk-js/tree/666-pure-and-secure-bip32-hdnode is pure and secure for

- packages/core/src/hdnode/hdnode.ts
- packages/core/src/mnemonic/mnemonic.ts

**Comment by lucanicoladebiasi** [comment]
The code at https://github.com/vechain/vechain-sdk-js/tree/666-pure-and-secure-utils-data is pure and secure for
- packages/core/src/utils/data/data.ts

The code in `packages/core/src/utils/const/data.ts` substitute `ZERO_BUFFER` based on NodeJS `Buffer` with `ZERO_BYTES` based on pure JS `Uint8Array`.

**Comment by nwbrettski** [comment]
Link to polyfills potential solution https://github.com/paulmillr/noble-hashes/issues/48

**Comment by victhorbi** [comment]
@rodolfopietro97 what are the problems you still see with NextJS?

cc @Valazan

**Comment by victhorbi** [comment]
Seems that compatibility was achieved, there are residual issues to be analysed more in depth but related to the test environment (jest). 

Relates to : #978

**Comment by rodolfopietro97** [comment]
Evaluate browser list in a second moment (not HP) @victhorbi
