### ISSUE TITLE
eth_getLogs - refinements

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#580]
According to the vechain node swagger, the logIndex and the transactionIndex are not returned. If, as reported, the only alternative is to query a block for every entry log, we can implement it in the eth_subscribe call, in which logs are referring just to one block (which is get before invoking eth_getLogs).

**Comment by victhorbi** [comment]
@rodolfopietro97 as you were suggesting, let's make sure to collect all the requirements for the protocol team.

**Comment by victhorbi** [comment]
replicated, can be closed like #1074
