### ISSUE TITLE
Create a set of development accounts for hardhat in testnet

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#629]
For internal use only create a mnemonic which will be used to fund 3 testnet accounts for hardhat development testing.

Tasks:
- [x] Create a mnemonic and 3 accounts
- [x] Fund those accounts with testnet funds (Contact @nwbrettski for funds)
- [x] Capture on Confluence and share with SDK team

**Comment by lucanicoladebiasi** [comment]
On testnet
- Alice at 0x91650716CAcC79C363db84bED773939a6086651b
   - 500 VET
   - 50 VTHO
- Bella at 0x9cB4F7d3bA012171B22bdDCfFFe314f88dfE2fA1
   - 500 VET
   - 50 VTHO
- Carol at 0x203bEE8E92278381fbEE7C601ebADa5Fb49D42c1   
   - 500 VET
   - 50 VTHO

**Comment by lucanicoladebiasi** [comment]
The mnemonic words represents the private key of the wallet. Hence
```
import { HDNode, mnemonic } from '@vechain/sdk-core';
const hdnode = HDNode.fromMnemonic(randomMnemonic);
```
returns the hierarchical deterministic root node representing the tree of keys of the wallet.
When the wallet generates accounts, keys and addresses of the accounts are deterministic, hence if accounts are added any time before of after the following code
```
for (let i = 0; i < 5; i++) {
    const child = hdnode.derive(i);
    console.log(`children ${i} address`, child.address);
    console.log(`children ${i} private key`, child.privateKey);
}
```
the `console` statements print the addresses and provate keys of the wallet they belong.
