### ISSUE TITLE
SDK Integration Testing :: dapp-kit

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#634]
Investigate the ability to use the SDK as a dependency for the dApp-kit instead of the existing connex, thor-devkit and other tools.

Tasks:
- Does the SDK provide the functionality required by the dApp-kit
- Do the dApp-kit tests pass with SDK as dependency
- Perform initial integration
- Polyfills implement on dApp-kit

Acceptance Criteria:
- dApp-kit can use the SDK as a dependency
- the issue https://github.com/vechain/vechain-dapp-kit/issues/237 should be solved as well by the PR that gets opened to solve this ticket

**Comment by rodolfopietro97** [comment]
https://github.com/vechain/vechain-dapp-kit/pull/252

**Comment by nwbrettski** [comment]
Blocked by #518

**Comment by victhorbi** [comment]
Blocked by #1050 since incompatibilities with Axios.

**Comment by victhorbi** [comment]
Unblocked by [#267](https://github.com/vechain/vechain-dapp-kit/pull/267)

**Comment by fabiorigam** [comment]
Thor-devkit has been removed now. Connex is still missing @rodolfopietro97. Please merge the opened PRs before proceeding, as they introduce changes to che connex implementation.
