### ISSUE TITLE
Common Parsing Approach

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#675]
We need to have a convention for parsing to different types to ensure that we have one approach currently there are various approaches implement.

Tasks:
- TBD

Acceptance Criteria:
- A single approach for parsing to have a single standard

**Comment by victhorbi** [comment]
@lucanicoladebiasi I think this issue is aligned with what you are currently doing, am I right?

**Comment by fabiorigam** [comment]
@lucanicoladebiasi is already working on that with the new changes on core package

**Comment by victhorbi** [comment]
Closed indirectly
