### ISSUE TITLE
Contract :: Implement multi clauses transactions

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-sdk-js#676]
Since Vechain supports multi clauses, we need to implement it in the contract loader siystem. 

The implementation could be something like this:

`contract.transact(multiclauses: true).function1().function2().function3().send()`

**Comment by ifavo** [comment]
@Valazan @darrenvechain sorry if I jump into your conversation, I found this issue after browsing some other issues, coming from a different but similar issue on simplifying transactions (https://github.com/vechain/vechain-sdk-js/issues/773#issuecomment-2037235200)

I personally like the `build` & `send` syntax most, but it will miss the ability to use different contracts within the same transaction.

I believe the second `clause` version would provide this but also needs the ability to pass in options for the transaction like delegation or transaction dependency.

Here's a more complex example I think should be possible:

```js
const tx = await thor.contracts.sendTransaction([
  clauseBuilder.transferVET(address, 100),
  contract1.mint(address, 1000).asClause(),
  contract2.mint(address, 1000).asClause(),
  clauseBuilder.transferToken(contract2.address, anotherAddress, 1000)
], privateKey, { delegatorUrl: '...' })
```

**Comment by Valazan** [comment]
@ifavo it's a very good observation. My proposal is to introduce a new clause proxy that creates a clause for each call. The result will be very similar:


``` typescript
const tx = await thor.contracts.sendTransaction([
  clauseBuilder.transferVET(address, 100),
  contract1.clause.mint(address, 1000),
  contract2.clause.mint(address, 1000),
  clauseBuilder.transferToken(contract2.address, anotherAddress, 1000)
], privateKey, { delegatorUrl: '...' })

```

**note**: with the introduction of the signer we could also avoid passing the private key

**Comment by ifavo** [comment]
@Valazan Your suggestions reads good to me, feels more natural now that I have tested the contracts loader.
