### ISSUE TITLE
Understand better ethers dependency handling

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#687]
Understand the extent of our dependencies on ethers.

Tasks:
- Create a confluence page listing out how and where ethers is used throughout the SDK.

**Comment by lucanicoladebiasi** [comment]
The survey of where [Ethers](https://docs.ethers.org/v6/) is used in the SDK is published at https://vechain.atlassian.net/wiki/spaces/TS/pages/531496965/Cryptographic+Security#State-of-Cryptography-in-SDK.
