### ISSUE TITLE
Understand how to test the RPC proxy

### ISSUE THREAD

**Issue by fabiorigam** [vechain/vechain-sdk-js#689]
A simple test to confirm that the RPC communication is working, the endpoint itself is tested with unit tests.

Tasks:
- Create a fixture of the parameters required for 5 of the 20 endpoints.
- During the CI workflow select 1 of the 5 endpoints, make a request if a 200 response if returned the test passes otherwise it fails.
- Confirm that the fixtures are all passing being implementing the random select of 1 of 5 for the CI workflow.

Acceptance Criteria:
- Integrated as part of the CI workflow and passing.

**Comment by nwbrettski** [comment]
Refinement meeting discussion.

Suggestion is to test each endpoint, of which there are 20, with the following:
- basic integration test of 1 of 5 random endpoints (make request, get 200 response, test passed)
   - this would require a fixture of the parameters for 5 specified endpoints.

**Comment by leszek-vechain** [comment]
ideally we could run it as part of integration suite (before e2e and deployment), so dev team can run it locally during development
