### ISSUE TITLE
Derive public key from Wallet extended public key without the need of the `elliptic` library.

### ISSUE THREAD

**Issue by lucanicoladebiasi** [vechain/vechain-sdk-js#712]
The [#105 Try to substitute secp256k1 using noble-secp256k1](https://github.com/vechain/vechain-sdk-js/issues/105) moves from `elliptic` lib to the secured `noble-curves` lib for cryptographic function.

The `elliptic` lib is used only to derive public keys from Wallet HD extended public keys hence no risk of security infringements, but the same functionalities seems to be implemented elsewhere in the SDK.

The [hdnode.ts](https://github.com/vechain/vechain-sdk-js/blob/main/packages/core/src/hdnode/hdnode.ts) code should provide the same functionalities through the `ether` lib without the need of the `elliptic` one.

**Comment by nwbrettski** [comment]
This would result in being able to remove the dependency `elliptic`

**Comment by lucanicoladebiasi** [comment]
Experimenting libraries
- [scure-base](https://github.com/paulmillr/scure-base)
- * [Security](https://github.com/paulmillr/scure-base?tab=readme-ov-file#security) audited.
- * Compatible [MIT License]()
- [scure-bip32](https://github.com/paulmillr/scure-bip32)
- * [Security](https://github.com/paulmillr/scure-bip32?tab=readme-ov-file#security) audited.
- * Compatible [MIT License](https://github.com/paulmillr/scure-bip32/blob/main/LICENSE).

to provide alternatives to `elliptic` libraries.

My notes so far:
- `Ether.js` not needed.
- `hdnode.ts` sould be refactored using the certified algorithms.- Tests must be rewritten because they do not test any HDNode key: extended keys only have the private or public components.

**Comment by lucanicoladebiasi** [comment]
`packages/core/src/secp256k1/secp256k1.ts` provides the `function randomBytes(bytesLength?: number | undefined): Buffer` as drop-in replacement for the same function provided by `crypto.js`.

The new implementation is based on [noble-hashes](https://github.com/paulmillr/noble-hashes) library, used for seckp256k1 ECDSA curve, hence
- [Security](https://github.com/paulmillr/noble-hashes?tab=readme-ov-file#security) audited.
- Compatible [MIT License](https://github.com/paulmillr/noble-hashes?tab=MIT-1-ov-file)

**Comment by lucanicoladebiasi** [comment]
The PR at https://github.com/vechain/vechain-sdk-js/pull/751 removes the deprecated [crypto-js](https://www.npmjs.com/package/crypto-js) vulnerabilities.

**Comment by lucanicoladebiasi** [comment]
The missing function to complete `noble-curves` with the functionalities of `elliptic` is the function inflating a compressed public key to its uncompressed form. My implementation in TS is
```
function inflate(compressedPublicKey: Uint8Array): Buffer {
    const a = new BN(_secp256k1.CURVE.a.toString());
    const b = new BN(_secp256k1.CURVE.b.toString());
    const p = new BN(_secp256k1.CURVE.p.toString());
    const prefix = compressedPublicKey[0];
    const x = new BN(compressedPublicKey.slice(1), 'hex');
    const y2 = x.pow(new BN('3')).add(x.mul(a)).add(b).umod(p);
    let y = y2.pow(p.addn(1).divn(4)).umod(p);
    const two = new BN(2);
    if (y.mod(two) !== new BN(prefix - 2)) {
        y = p.sub(y);
    }
    return Buffer.concat([
        Buffer.from([0x04]), // Prefix byte for uncompressed key
        Buffer.from(x.toArray()), // X-coordinate
        Buffer.from(y.toArray()) // Y-coordinate
    ]);
}
```
using the secp256k1 constants provided by the `noble-curves` library.
The math at the base of the transformation is published at https://www.secg.org/sec2-v2.pdf, hence the above function can be certified.
The mathematician developed the `noble-curve` library thought is trivial hence omitted to implement the function.
