### ISSUE TITLE
Wallet Buddy for Sync2

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#726]
This is a requirement for sync2 and the dapp-kit.

Questions:
- What is this, why do we need it?
- If we need to support it what is the scope and context?

**Comment by victhorbi** [comment]
@rodolfopietro97 I think we should check compatibility after we are confident browser compatibility is achieved, what do you think?

**Comment by fabiorigam** [comment]
@victhorbi This code essentially provides a way for developers to integrate Sync (our old VeChain wallet) functionality into their applications, allowing users to sign transactions or certificates using their Sync wallet. 
Now we have dApp kit, so no need to implement this on the SDK.
