### ISSUE TITLE
Docs update package reference

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#737]
The docs examples all make reference to `vechain-sdk-xxx` whereas it should reference `sdk-xxx`.

Tasks:
- Update the references throughout the SDK docs

**Comment by fabiorigam** [comment]
@nwbrettski Can you give examples? I could find only https://github.com/vechain/vechain-sdk-js/pull/741

**Comment by nwbrettski** [comment]
@fabiorigam sure. Please see the first line of the snippet here, https://docs.vechain.org/developer-resources/sdks-and-providers/sdk/accounts. I believe all of the snippets use the `vechain-sdk-xxx` whereas they should be using `sdk-xxx`.

**Comment by fabiorigam** [comment]
Now I understand. That was changed on this repo but not updated on the docs, I'll do it, thanks!

**Comment by fabiorigam** [comment]
@nwbrettski https://github.com/vechain/vechain-docs/pull/35
