### ISSUE TITLE
🐛 [BUG] - VechainProvider QUANTITY|TAG does not support objects

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#749]
### Description

According to the RPC documentation certain RPC methods accept a block reference as parameter. 

Specified here: https://eips.ethereum.org/EIPS/eip-1898#specification

The argument of a blockHash like `{ "blockHash": "0x.." }` is not supported, it requires to be passed as string instead.

### Reproduction steps

Run RPC Proxy with MainNet connection and do  `eth_call` for a specific blockHash:

```bash
$ curl -XPOST "http://localhost:8545" -H "content-type: application/json" -d '
{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [{"data":"0x06fdde03","gas":"0x2faf080","to":"0x4e17357053da4b473e2daa2c65c2c949545724b8"},{"blockHash":"0x00a976aa7a396c0112ecc3827d6abab2d8544d6c3506725ee8da85e32ea8f036"}],
    "id": "1"
}
'
```

The correct result should be:

```json
{"jsonrpc":"2.0","id":"1","result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000055665555344000000000000000000000000000000000000000000000000000000"}
```

**Comment by Valazan** [comment]
Thank you @ifavo for reporting this issue. We will have a look into it!
