### ISSUE TITLE
Windows Compatibility Issues

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#759]
There are reports of incompatibility issues on Windows.

Questions:
- Where are the incompatibility issues.

**Comment by lucanicoladebiasi** [comment]
### OS specific script diagnosis.

The file `apps/sdk-node-integration/package.json` defines in the `scripts.build` the linux/unit specific command
```
rm -rf ./dist && tsup src/index.ts --format cjs,esm --dts
```
to be executed in the OS shell/terminal. Both the command `rm` invoked and the way the arguments are passed with `--` are OS specific, where Windows uses `del` for `rm` and `/` for `-`.

### Proposed therapy.

SDK is supposed to be installed with `git`, part of most Unix derived distributions. 
*Git* must be specifically installed in Windows
The official porting of *Git* for Windows is available at https://git-scm.com/download/win.
The installation deploys in Windows the  [](https://www.mingw-w64.org/) terminal, providing a terminal compatible with the [bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) shell.
Running `yarn` commands from Windows - Start -`Git Bash` will succeeds to build and run both the SDK and Thor.

**Comment by lucanicoladebiasi** [comment]
### On Docker-Desktop in Windows 10.

Docker-Desktop (tested v4.28.0) needs Windows 10 to be patched

**Comment by leszek-vechain** [comment]
would something like that be useful ? it seems it can handle different systems

- https://www.npmjs.com/package/rimraf

**Comment by nwbrettski** [comment]
Short term let's go ahead with you above proposed solution.

Long term we need to be OS agnostic to avoid having OS users to perform different tasks.
