### ISSUE TITLE
Hardhat Plugin :: Implement impersonated signer

### ISSUE THREAD

**Issue by Valazan** [vechain/vechain-sdk-js#778]
Currently, the Hardhat impersonated signer, it's not implemented in our hardhat plugin.

Hardhat Network allows you to impersonate any address. This lets us send transactions from that account even if we don't have access to its private key.

An analysis must be done to understand how to implement this feature.

https://hardhat.org/hardhat-network/docs/guides/forking-other-networks

**Comment by Valazan** [comment]
I had a discussion with @Agilulfo1820. They don't need this feature at the moment (they are not using it at all). I'll put it into pause to focus on more prioritary tasks.

**Comment by victhorbi** [comment]
Let's consider it out of scope, given the effort.
