### ISSUE TITLE
💡 Contracts :: Read value for revision

### ISSUE THREAD

**Issue by darrenvechain** [vechain/vechain-sdk-js#827]
### Summary

We should be able to read values in smart contracts for a particular point in time, by providing a block ID or number as a revision.

### Basic Example

```typescript

const blockNumber = 1000;

const balance = await contract.read.balanceOf(
    "0x3504c0089Ce44d5709BB97a957EC40C76F18dCdA", { revision: blockNumber}
);
```

**Comment by darrenvechain** [comment]
Looks like this would require an interface change:

<img width="1764" alt="image" src="https://github.com/vechain/vechain-sdk-js/assets/107671032/a88777d8-cc66-465a-92f9-348f525ce6eb">

**Comment by ifavo** [comment]
@darrenvechain what about making the options compatible to the [`ContractCallOptions`](https://tsdocs.dev/docs/@vechain/sdk-network/1.0.0-beta.3/types/network.ContractCallOptions.html) on `executeContractCall`? It basically allows to do a simulation
