### ISSUE TITLE
💡 [REQUEST] - Improve serverless (especially CloudFlare) support

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#830]
### Summary

My personal setup involves [CloudFlare Workers](https://developers.cloudflare.com/workers/) a lot to create APIs or Vechain interaction with a very low effort.
To enable transaction building with connex I have a stripped version of the [`thor-devkit`](https://github.com/vechain-energy/oracle.vechain.energy/tree/main/reporter/src/modules/thor-devkit) that runs in `node_compat` (NodeJS compatibility) mode.

I would like to use the SDK within CloudFlare Workers in compatibility mode as well without creating a stripped version to:

1. Build transaction objects
2. Sign transactions
3. Interact with the Node-APIs

Ideas to create the compatibility are:

1. Use global fetch or allow injection of fetch function
2. Dynamically import modules, like `events` on demand instead

### Basic Example

1. Create a new CloudFlare Worker using `npx wrangler generate sdk-cf`
5. Add `@vechain/sdk-network` to it using `npm install --save @vechain/sdk-network @vechain/sdk-core`
6. Create a thor client in the worker using `ThorClient.fromUrl('https://testnet.vechain.org')`
7. Test the Worker by using `wrangler dev` or if you have a CloudFlare account use `wrangler deploy`
   - It will fail to start.
   - _Optimal Results would be a CloudFlare Worker that can use the SDK instantly without enable Node Compatibility in the next step._
8. Add `node_compat = true` to the `wrangler.toml` to enable NodeJS compatibility
9. Test the Worker by using `wrangler dev` or if you have a CloudFlare account use `wrangler deploy`

Using this simplified `index.ts`:

```ts
import { ThorClient } from "@vechain/sdk-network";
export default {
	async fetch(
	): Promise<Response> {
		const thor = ThorClient.fromUrl('https://testnet.vechain.org')
		const block = await thor.blocks.getBestBlockRef()
		return new Response(block);
	},
};
```

**Comment by victhorbi** [comment]
Hello @ifavo , 
With `node_compat` enabled, are you able to run the worker?

**Comment by ifavo** [comment]
No it won't.

**Comment by ifavo** [comment]
I've opened a new issue: https://github.com/vechain/vechain-sdk-js/issues/1095

From my perspective we can close this issue, because it did not contain the signing as requirement.
