### ISSUE TITLE
Research - Revert reason of confirmed tx

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#844]
The issue is a reaserch task to design the improvement linked to the reported issue: 
https://github.com/vechain/vechain-sdk-js/issues/438

The expected result will be to unblock the issue and proceed with the write up of the documentation.

This issue can be spliced into two parts:

- [x] Get the revert reason of a reverted transaction into transactions module

**Comment by rodolfopietro97** [comment]
Issue #829
