### ISSUE TITLE
Research - Dapp-kit requirements for SDK Integration Testing

### ISSUE THREAD

**Issue by victhorbi** [vechain/vechain-sdk-js#845]
In order to proceed with the issue:
https://github.com/vechain/vechain-sdk-js/issues/634

It's required to clarify which information are used by the dapp-kit and wallet, and in which format.

**Comment by darrenvechain** [comment]
@victhorbi @Valazan I have a branch here: https://github.com/vechain/vechain-dapp-kit/tree/initial-sdk-integration
