### ISSUE TITLE
Rationalise Testing Accounts & Strategy

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#858]
We need to migrate our testing accounts off thor solo accounts and use some specified and SDK team owned and controlled accounts.

Tasks:
- Reduce the amount of accounts that are used as part of the tests
- Run the tests and have them pass

Acceptance Criteria:
- A reduced set of thor solo accounts to optimize and perform our tests

Links:
- https://vechain.atlassian.net/wiki/spaces/TS/pages/488636423/Accounts

**Comment by nwbrettski** [comment]
Pulling this back as the QA team are coming up with an idea on how to make a standard library for use by all products.

**Comment by lucanicoladebiasi** [comment]
Testing the [e2e-utils](https://github.com/vechain/e2e-utils/tree/clayton/review) to create One Time Use (OTU) account in Thor.

**Comment by lucanicoladebiasi** [comment]
We tsted the e2e-utils with @leszek-vechain and agreed the following.

1. A `npm` library will be published to let SDK to import the specialized client to connect with the e2e-utils service to create one-time-use accounts and get its coordinates for tests.
2. The `account-server:` section of `e2e-utils` at `docker-compose.yml` must be imported in the `docker-compose.yaml` of `vechain-sdk-js` but to do this, the *thor-solo* image must be pulled by docker-hub and referenced in `account-server:image` tag of the docker compose YAML configuration file. This action will let the SDK to start *thor-solo( and the *e2e-utils* service and allow the SDK test code to connect with the ad-hoc account generation service.

Few bugs solved and suggestions discussed.

**Comment by lucanicoladebiasi** [comment]
From today (23/8/2024) stand-up, @leszek-vechain reports needed changes won't be available before the end of this week. Preparing the test code for `e2e-utils` meanwhile.

**Comment by leszek-vechain** [comment]
The account manager docker image is here:

https://github.com/vechain/e2e-utils/pkgs/container/e2e-account-manager

I think we should be able to include it in sdk docker-compose.yaml

npm client should be ready soon

**Comment by leszek-vechain** [comment]
The dependency for e2e utils is here:

https://github.com/vechain/e2e-utils/pkgs/npm/e2e-utils

so now we should be able to use it together

**Comment by lucanicoladebiasi** [comment]
Resuming this ticket after core refactoring.
I use https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API as REST library instead of `axios`.

**Comment by leszek-vechain** [comment]
yeah thats good idea to switch it to fetch, axios was selected as it was done during prototyping :D

**Comment by victhorbi** [comment]
We will open a more specific new ticket when all the refactor will be done.
