### ISSUE TITLE
Not able to change the port of proxy

### ISSUE THREAD

**Issue by AthiraVGopi** [vechain/vechain-sdk-js#871]
### Description

I tried to change the port number in the config.json, but not working always running in default one

### Reproduction steps

```bash
{
    "url": "https://node-mainnet.vechain.energy",
    "port": 8080
}
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by fabiorigam** [comment]
> ### Description
> I tried to change the port number in the config.json, but not working always running in default one
> 
> ### Reproduction URL
> _No response_
> 
> ### Reproduction steps
> ```shell
> {
>     "url": "https://node-mainnet.vechain.energy",
>     "port": 8080
> }
> ```
> 
> ### Screenshots
> ```shell
> ![DESCRIPTION](LINK.png)
> ```
> 
> ### Logs
> _No response_
> 
> ### OS
> _No response_

Hello @AthiraVGopi, as you can see from the file types.d.ts, account parameter is required in the configuration (in addition to the url and port). So, if you start the RPC Proxy without the "accounts" param you'll get an error.
Example of a working config:
```shell
{
    "url": "http://127.0.0.1:8669",
    "port": 8080,
    "accounts": {
        "mnemonic": "denial kitchen pet squirrel other broom bar gas better priority spoil cross",
        "count": 10
    }
}
```
In this case it's working on port 8080 as expected.
