### ISSUE TITLE
Proxy always running on default port 

### ISSUE THREAD

**Issue by AthiraVGopi** [vechain/vechain-sdk-js#872]
### Description

Hi I only have a config.json in root directory and index.js in src in my folder.
in my nodemoudules " import importConfig from '../config.json'; " this one is showing error as " Cannot find module '../config.json' or its corresponding type declarations.ts(2307)" . How can I solve this to use my config.json properly. not working as expected now.

### Reproduction steps

```bash
config.json
{
    "url": "https://node-mainnet.vechain.energy:8669",
    "port": 8080,
    "accounts": {
        "mnemonic": "denial kitchen pet squirrel other broom bar gas better priority spoil cross",
        "count": 10
    }
}

index.js
const fs = require('fs');
const { VeChain } = require('@vechain/sdk-rpc-proxy');

const config = JSON.parse(fs.readFileSync('./config.json', 'utf8'));
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by fabiorigam** [comment]
@AthiraVGopi What are you trying to do?
If you want to use the vechain RPC Proxy, all you have to do is clone the sdk repo, cd into packages/rpc-proxy, configure the config.json file, and run "yarn" and "yarn start". This is the ONLY way to use the proxy.
This package is not exporting anything, so you can't create a new file, import it and use it.
