### ISSUE TITLE
chore: 100% coverage on vns new code

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#885]
Currently VNS code has not 100% coverage.
So make the proper tests to increase it

**Comment by ifavo** [comment]
@rodolfopietro97 I have added some mock tests, I have verified the coverage report in `coverage/lcov-report` to show 100% coverage:

![Bildschirmfoto 2024-05-21 um 21 53 54](https://github.com/vechain/vechain-sdk-js/assets/407503/92a3d0ea-dd26-4afb-9cdd-752ce522676e)

I was unable to test the missing configuration / missing genesis information. Which I could do with the new mock test. Also used this chance to add tests for the contract calls, which were previously covered by testing results but ensuring the contract call is correct, is a better way to verify its behaviour.

If there is anything left or you'd like to improve, please let me know!

**Comment by ifavo** [comment]
I just realized that the signer needs an additional test for missing providers and the transaction module for default values as well. Apologies for the premature delivery! Will add those too.

**Comment by ifavo** [comment]
@rodolfopietro97 I have added additional tests to cover the error handling in the VechainProvider and to cover the missing statement in the transaction module. Both show a 100% coverage again.
