### ISSUE TITLE
SDK Docs Naming Standard

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#894]
Update the SDK docs naming standards to be the following:

- VeChain
- VeChainThor

**Comment by ifavo** [comment]
@nwbrettski May I suggest to review the naming standards in all places, also outside of this project, for example on https://www.vechain.org/ there are different versions:

- Vechain Foundation San Marino
- VeChain Foundation is the curator..
- VechainThor Blockchain
- VeChainThor Blockchain
- VeChain powered solutions
- Vechain's energy consumption

… mixed in all cases just on the homepage.

**Comment by nwbrettski** [comment]
I completely agree @ifavo this is a particularly annoying. There should be consistency in the naming standard. We are updating the website and this should be rectified as part of the update.

I believe the use of lowercase `vechain` is acceptable but I must admit I am not sure of the particulars when to use `VeChain` as opposed to `vechain`. On the SDK we have opted to only use `VeChain` and `VeChainThor`.
