### ISSUE TITLE
Document & Diagram Release Process

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#913]
We need to document and a supporting diagram of the release process to identify all of the steps in the process.

Tasks:
- Document the release process steps in a confluence document
- Provide a diagram

Acceptance Diagram:
- A well document process to follow to ensure all steps in the release process are clear and followed for each release.

**Comment by fabiorigam** [comment]
https://vechain.atlassian.net/wiki/spaces/TS/pages/621510673/How+to+Release+a+new+version
