### ISSUE TITLE
Enforce GPG Keys

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#914]
GPG keys should be required on all PRs raised.

Tasks:
- Enable and enforce GPG keys to be required.

Acceptance Criteria:
- Only submissions from participants with a GPG key will be allowed.

**Comment by rodolfopietro97** [comment]
@nwbrettski you mean signed commits?
If yes I can enable on the fly that 

![Image](https://github.com/vechain/vechain-sdk-js/assets/33911400/f9159cf3-e98d-49b7-aed2-3dc0e21b26a3)
