### ISSUE TITLE
HardHat network support

### ISSUE THREAD

**Issue by fabiorigam** [vechain/vechain-sdk-js#923]
At the moment the HardHat package of the SDK only supports VeChain networks. It should also support the default HardHat network.

**Comment by nwbrettski** [comment]
@fabiorigam is this a duplicate of https://github.com/vechain/vechain-sdk-js/issues/932. The linked issue doesn't have a description which isn't ideal but I think the implementation of this issue has been completed.

**Comment by fabiorigam** [comment]
Already implemented
