### ISSUE TITLE
🐛 [BUG] - parseUnits(formatUnits())  results in a different number

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#927]
### Description

I have a big int number that is converted correctly to a human readable version using `formatUnits` but when applying `parseUnits` on the same string, it does return a different number. There might be a rounding error at a certain point.

### Reproduction steps

```js
import { unitsUtils } from '@vechain/sdk-core';

const bintBalance = 398913019603365720000n
console.log(unitsUtils.parseUnits(parseFloat(unitsUtils.formatUnits(bintBalance)), 18))
```

It results in:

- `398913019603365740000n` but should be `398913019603365720000n`
- compared the same process with `ethers`, which works correctly as expected

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by ifavo** [comment]
I am sorry, I was a bit too early, using parseFloat is an error I did and did not test in the ethers comparison. All good an no issue here. Sorry again.

**Comment by lucanicoladebiasi** [comment]
Never less, I'm going to investigate a possible side effect because the `decimal` library backing the parseUnit has a global variable to set the precision, this could lead to side effects poking with the same library in other parts of a project using our SDK and `decimals`.

**Comment by ifavo** [comment]
I created a second issue with reproduction code here: https://github.com/vechain/vechain-sdk-js/issues/928 - maybe best to handle it there?

**Comment by lucanicoladebiasi** [comment]
This ticket is closed because investigation moved to https://github.com/orgs/vechain/projects/9/views/1?pane=issue&itemId=65498793 as suggested.
