### ISSUE TITLE
🐛 [BUG] - parseUnits throws on numbers below `0.1`

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#928]
### Description

When I use `parseUnits` on numbers below `0.1` it throws with:

for example `0.000000000000000001`:

```js
-Reason: 'Cannot convert 1.00000000000000000 to a BigInt'
-Parameters: 
	{"value":"0.000000000000000001","decimalsOrUnit":18}
-Internal error: 
	Cannot convert 1.00000000000000000 to a BigInt
```

On val.town I have made an example showing different numbers comparing the result with ethers, whose results are as expected.

```js
import { unitsUtils } from "npm:@vechain/sdk-core";
import * as ethers from "npm:ethers";

const numberStrings = [
  "0.100000000000000000",
  "0.000000000000000001",
  "0.099999999999999999",
  "0.001000000000000000",
];

numberStrings.forEach(str => {
  console.log("ethers:", str, "=>", ethers.parseUnits(str, 18));
  try {
    console.log("vechain:", str, "=>", unitsUtils.parseUnits(str, 18));
  }
  catch (err) {
    console.log("vechain:", str, "failed", err.message);
  }

  console.log("----\n\n");
});
```

### Reproduction URL

https://www.val.town/v/ifavo/parseUnits

### Reproduction steps

```ts
import { unitsUtils } from "@vechain/sdk-core";

const str = "0.000000000000000001"
console.log( unitsUtils.parseUnits(str, 18)) )
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by lucanicoladebiasi** [comment]
I confirm the problem, diagnosed because a bug in the representation of meaningful digits. I included the tests proposed by @ifavo I sincerely thank. Testing the solution, and documenting side effects possible poking `BigNumber` global settings. Releasing next.

**Comment by ifavo** [comment]
Thank you checking this so quickly and providing feedback 🙏

**Comment by lucanicoladebiasi** [comment]
The https://github.com/vechain/vechain-sdk-js/pull/936 includes the fix and solves global setting collisions of `BigNumber` functionalities altering the correctness of the `unitUtils` functions. Suggested tests are introduced to compare `ethers` behaviour with SDK replacement functions.

**Comment by ifavo** [comment]
@lucanicoladebiasi thanks a lot for the update and quick fix 🙏 

which release will likely contain the update?
