### ISSUE TITLE
Transaction Preview

### ISSUE THREAD

**Issue by nwbrettski** [vechain/vechain-sdk-js#939]
As a user I want to be able to view a preview of a transaction / clause so that I can understand and view what function and action the transaction / clause is going to perform.

Tasks:
- Add the optional field `comment` and `abi`

Acceptance Criteria:
- The ability to preview the transaction function and parameters.

**Comment by ifavo** [comment]
@nwbrettski is this linked to https://github.com/vechain/vechain-sdk-js/issues/805 ?

**Comment by nwbrettski** [comment]
@ifavo yes I think this is a duplicate of https://github.com/vechain/vechain-sdk-js/issues/805 I will remove this as a duplicate and add this to the Product Backlog in it's place. 805 existed before hence this is the duplicate item.
