### ISSUE TITLE
🐛 [BUG] - `eth_getTransactionCount` returns random numbers

### ISSUE THREAD

**Issue by ifavo** [vechain/vechain-sdk-js#942]
### Description

When accessing `eth_getTransactionCount` on the RPC Mapper, there is a random number returned at all times.

https://github.com/vechain/vechain-sdk-js/blob/630d4028096de84d82ea2176985c086cfd9acb03/packages/network/src/provider/utils/rpc-mapper/methods-map/methods/eth_getTransactionCount/eth_getTransactionCount.ts#L46

This might be sufficient for applications using only the number or for test cases, but not for applications relying on the counter, like `hardhat-ignition` does.

For example hardhat-ignition fails to interact with vechain networks, because it detects pending transactions that do not exist.

I suggest to:

1. Either return `0` at all times or return the current block number
2. and add [Transaction Pool](https://node.vechain.energy/doc/stoplight-ui/#/paths/transactions-pending/get) and filter for the request address, to return a meaningful number in the pending request

As reference, here are requests within ignition that result in invalid conditions:

https://github.com/NomicFoundation/hardhat-ignition/blob/development/packages/core/src/internal/execution/nonce-management/get-nonce-sync-messages.ts#L89-L112

### Reproduction steps

```bash
curl -s https://rpc-testnet.vechain.energy/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getTransactionCount","params":["0x202bB937Af984F83184B726cDc099A76d8bcDE8b", "pending"],"id":1,"jsonrpc":"2.0"}' | jq
```

Returns a value, even if there is nothing pending:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x53aebba70699"
}
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by victhorbi** [comment]
Hello @ifavo , 
Until we have the information coming from either the node or an indexer, the VeChain-SDK can't provide a solution that will provide a reliable transaction count always, unless either indexing all the information locally or making tons of requests backwards until genesis.

As you know, the method should return the number of transactions that overall, a specified address has done up to the specified block.

We can instead allocate a local storage that will initialize at 0 and increment the counter for each transaction of the same wallet address client side. The SDK will require to store a record keeping also the block height for each transaction, to have enough information for requests referring to a previous block.

Do you consider it viable?

**Comment by ifavo** [comment]
@victhorbi I understand the current issues and that there is no good solution right now.
I don't believe starting a data storage is a good idea.

Until there is one, what are your thoughts about returning a zero or the block number instead of a random number?

**Comment by victhorbi** [comment]
Mostly that a wallet or dapp designed with Ethereum in mind might wait indefinitely for that number to change after a transaction

**Comment by ifavo** [comment]
> Mostly that a wallet or dapp designed with Ethereum in mind might wait indefinitely for that number to change after a transaction

If it increases with the block numbers, it will detect a change. Right now those apps, would be failing because the new number will randomly be smaller too. So this is hypothetical issue, not an existing one, right?

**Comment by victhorbi** [comment]
> If it increases with the block numbers, it will detect a change. Right now those apps, would be failing because the new number will randomly be smaller too.
Correct. We should improve the method to increase interoperability with existing tooling and dapps for Ethereum.

> Apps like those are also using it as nonce, are there any (official) on vechain parts in the SDK that rely on this rpc implementation for nonce generation?
No, AFAIK.

**Comment by victhorbi** [comment]
Not a bug, it's the behaviour that is aligned with Ethereum in terms of process, with VeChain for how it works. 
Will accomodate the request separately with ticket #1360 .
