### ISSUE TITLE
fix: Solve issue of Uint8Array and Polyfilling

### ISSUE THREAD

**Issue by rodolfopietro97** [vechain/vechain-sdk-js#963]
- [x] Solve uint8 array and others polypill problems on Dappkit and on SDK

Document how to use SDK and Dappkit into browser environment --> moved in a separate ticket #975

**Comment by victhorbi** [comment]
Eventually was not a problem of cryptographic library. 
No polyfilling was required.
The documentation to be produce will document how to configure the test environment.
