### ISSUE TITLE
💡 [BREAKING CHANGES] Get Account :: Utility functions

### ISSUE THREAD

**Issue by darrenvechain** [vechain/vechain-sdk-js#998]
### Summary

It would be nice if getAccount returned a class or an object with some utility functions built in so it is easier to debug and read account balances etc.

Current code:
```typescript
// Returns {balance, energy, hasCode}
const account = await client.accounts.getAccount(account)
```

### Basic Example

It would be nice to have some extra functions such as:

```typescript
const account = await client.accounts.getAccount(account)
console.log(account.parsedVet()) //if my VET balance is `0x43c33c1937564800000`, then it prints `20000`
```

**Comment by claytonneal** [comment]
Its unclear to me why we return hex strings for getAccount for the VET & VTHO balance
perhaps to consider to change the AccountDetail interface so that balance and energy are of type BigNumber
thanks

**Comment by lucanicoladebiasi** [comment]
Since I reworked che address introducing a full fledged class 'Address' extending 'HEX', I suggest I. take the responsibility of such task implementing what missing and required.

**Comment by fabiorigam** [comment]
No problem Luca

**Comment by nwbrettski** [comment]
@lucanicoladebiasi has implemented using the OO approach. Will showcase as a demo during the refinement session.

**Comment by lucanicoladebiasi** [comment]
The solution I propose is

to rename the rename the interface `AccountDetail` in `AccountData` in `packages/network/src/thor-client/accounts/types.d.ts`, the interface is needed as container of data to cast the unknown object from
```
(await this.thor.httpClient.http(
                'GET',
                thorest.accounts.get.ACCOUNT_DETAIL(address),
                {
                    query: buildQuery({ revision: options?.revision })
                }
            )) as AccountData
```
in the method `getAccount` of the class `AccountsModule` at `packages/network/src/thor-client/accounts/accounts-module.ts`

Renaming `AccountDetail` to `AccountData` free the name to be used to implement the `AccountDetail` class in the file `packages/network/src/thor-client/accounts/accounts-module.ts`.
The class implements `AccountData` hence the solution preserves back compatibility.
The class exposes the computed properties
```
     /**
     * Returns the balance of the account in {@link VET}.
     */
    get vet(): VET {
        return VET.of(Units.formatEther(FixedPointNumber.of(this.balance)));
    }

    /**
     * Returns the energy balance of the account in {@link VTHO}.
     */
    get vtho(): VTHO {
        return VTHO.of(Units.formatEther(FixedPointNumber.of(this.energy)));
    }
```
returning objects of the **VeChain Data Model** type.

See at `packages/network/tests/thor-client/accounts/accounts.solo.test.ts` to see the proposed solution in action.
